/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiagu_bserver_util */

#ifndef _Included_com_jiagu_bserver_util
#define _Included_com_jiagu_bserver_util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiagu_bserver_util
 * Method:    UartOpen
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_jiagu_bserver_util_UartOpen
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_jiagu_bserver_util
 * Method:    UartClose
 * Signature: (Ljava/io/FileDescriptor;)V
 */
JNIEXPORT void JNICALL Java_com_jiagu_bserver_util_UartClose
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
